# Generated by Django 4.2 on 2023-07-16 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Volunteers',
            new_name='Volunteer',
        ),
    ]
