# Generated by Django 4.2 on 2023-07-16 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_volunteers_volunteer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Volunteer',
        ),
    ]
