# Generated by Django 4.2 on 2023-07-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_delete_volunteer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp_number', models.CharField(max_length=14)),
                ('age', models.CharField(max_length=2)),
                ('department', models.CharField(max_length=40)),
                ('months_of_experience', models.CharField(max_length=15)),
                ('will_be_available_for_bootcamp', models.CharField(max_length=3)),
                ('is_a_member_of_LTA', models.CharField(max_length=4)),
                ('how_did_you_hear_of_us', models.CharField(max_length=30)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Volunteers',
                'ordering': ('-date_registered',),
            },
        ),
    ]
